# Generated by Django 6.0.5 on 2026-06-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionprofile',
            name='dashboard_index_path',
            field=models.CharField(default='/dashboard/index.html', max_length=200),
        ),
        migrations.AddField(
            model_name='connectionprofile',
            name='health_path',
            field=models.CharField(default='/health', max_length=200),
        ),
        migrations.AddField(
            model_name='connectionprofile',
            name='monitoring_path',
            field=models.CharField(default='/monitoring', max_length=200),
        ),
        migrations.AddField(
            model_name='connectionprofile',
            name='request_timeout_ms',
            field=models.PositiveIntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='connectionprofile',
            name='version_path',
            field=models.CharField(default='/version', max_length=200),
        ),
    ]
