# Generated by Django 6.0.5 on 2026-06-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('BENCHMARK', 'Benchmark'), ('PROBE', 'Probe'), ('SYSTEM', 'System'), ('SUMMARY', 'Summary')], default='BENCHMARK', max_length=30)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('GENERATING', 'Generating'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='CREATED', max_length=30)),
                ('output_format', models.CharField(choices=[('JSON', 'JSON'), ('CSV', 'CSV'), ('MARKDOWN', 'Markdown'), ('HTML', 'HTML')], default='JSON', max_length=30)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
